[game]
hostname = "‚ãÜ MRI Station[MRP][+18][RU]"
desc = "MRI Station ‚Äî –º–µ—Å—Ç–æ, –≥–¥–µ —Ç—ã —Ä–µ—à–∞–µ—à—å —Å—É–¥—å–±—É!\n\nüë§ - –¢—ã –º–æ–∂–µ—à—å –æ—Ç—ã–≥—Ä–∞—Ç—å –ª—é–±–æ–π —Å—Ü–µ–Ω–∞—Ä–∏–π, –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–∏–¥—ë—Ç —Ç–µ–±–µ –≤ –≥–æ–ª–æ–≤—É. ( –ö—Ä–æ–º–µ —Ç–µ—Ö, —á—Ç–æ –Ω–∞—Ä—É—à–∞—é—Ç –ø—Ä–∞–≤–∏–ª–∞ )\n\nüßë‚Äçüíª - –ü–æ–Ω–∞–±–ª—é–¥–∞—Ç—å –∑–∞ –ª—é–¥—å–º–∏ –∏ –æ—â—É—Ç–∏—Ç—å –≤—Å—é –º–æ—â—å RP.\n\nüò≠ - –ü–æ–ª—É—á–∏—Ç—å –ø–æ–º–æ—â—å –æ—Ç –¥–æ–±—Ä–æ–¥—É—à–Ω–æ–≥–æ —Å–æ—Å—Ç–∞–≤–∞ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏, –µ—Å–ª–∏ —Ç—ã –Ω–æ–≤–∏—á–æ–∫ –∏ –Ω–µ —Ä–∞–∑–±–∏—Ä–∞–µ—à—å—Å—è –≤ –º–µ—Ö–∞–Ω–∏–∫–∞—Ö –∏–≥—Ä—ã.\n\nüìù - –ú—ã –æ—Ç–∫—Ä—ã–ª–∏—Å—å –Ω–µ–¥–∞–≤–Ω–æ –∏ –ø–ª–∞–Ω–∏—Ä—É–µ–º —Ä–∞–∑–≤–∏–≤–∞—Ç—å—Å—è, –¥–æ–±–∞–≤–ª—è—è —É–Ω–∏–∫–∞–ª—å–Ω—ã–µ —Ä–æ–ª–∏ –∏ —Å–æ–±—ã—Ç–∏—è.\n\n‚ú® - –ü—Ä–∏—Å–æ–µ–¥–∏–Ω—è–π—Å—è –∫ –Ω–∞–º –≤ Discord –∏ —Å—Ç–∞–Ω—å —á–∞—Å—Ç—å—é –Ω–∞—à–µ–π –º–∞–ª–µ–Ω—å–∫–æ–π, –Ω–æ —Å–∏–ª—å–Ω–æ–π —Å–µ–º—å–∏! "
maxplayers = 40
soft_max_players = 30
map_rotation = true
lobbyduration = 240
round_restart_time = 180
fallbackpreset = "extended"
lobbyenabled = true
role_timers = false
contraband_examine = false

[infolinks]
discord = "https://discord.gg/KKeeVEU3rg"


[server]
lobby_name = "MRI Station"
rules_file = "MRIRuleset"

[admin]
see_own_notes = true
admins_count_in_playercount = true

[rules]
time = 30.0

[hub]
advertise = true
tags = "lang:ru,region:eu_e,region:luna,region:as_n,rp:low,rp:med,"

[vote]
restart_required_ratio = 0.50
same_type_timeout = 300.0
timerrestart = 60
map_enabled = true

[ic]
flavor_text = true
punctuation = true

[ghost]
role_time = 10

[discord]
# Webhook to send adminhelp messages to.
ahelp_webhook = "https://discord.com/api/webhooks/1407453183977979994/4I4kKGOEuYtzI68f5cgWwp_1GlmfSvEtDJHIn6YTOlPw7MrYK91wKqIn1OWMM0alaxZa"

# Webhook to send round status messages to.
round_update_webhook = "https://discord.com/api/webhooks/1407452914750062734/jdR7sutozxgKfSdul0FGUPQF2xEp167gELVvIUE_CBx1OQkZrnY-gZs_CMCgHWQ-wv97"

# Optionally, a role ID to ping when the round has ended.
round_end_role = "1407478729885880369"